import { Bell, LogOut, Search, Settings } from "lucide-react";
import { useNavigate, useLocation } from "react-router-dom";

const Navbar = () => {
  const navigate = useNavigate();
  const location = useLocation();

  const handleLogout = () => {
    localStorage.removeItem("token");
    navigate("/login");
  };

  // Get dynamic title based on path
  const getPageTitle = (path: string) => {
    if (path.startsWith("/dashboard")) return "Welcome Back 👋";
    if (path.startsWith("/mock-interview")) return "AI Mock Interviews";
    if (path.startsWith("/dsa")) return "DSA Prep Suite";
    if (path.startsWith("/questions")) return "DSA Question Repository";
    if (path.startsWith("/editor")) return "Code Playground";
    if (path.startsWith("/progress")) return "Consistency & Achievements";
    if (path.startsWith("/resume-analyzer")) return "ATS Resume Analyzer";
    if (path.startsWith("/analytics")) return "Performance Analytics";
    if (path.startsWith("/voice-interview")) return "AI Voice Interviewer";
    if (path.startsWith("/ai-review")) return "AI Code Reviewer";
    return "Dashboard";
  };

  const getPageSub = (path: string) => {
    if (path.startsWith("/dashboard")) return "Here is a snapshot of your placement preparation.";
    if (path.startsWith("/mock-interview")) return "Practice real-time technical interviews generated by AI.";
    if (path.startsWith("/dsa")) return "Master coding interviews by practicing company-specific challenges.";
    if (path.startsWith("/questions")) return "Practice top-tier algorithmic challenges.";
    if (path.startsWith("/editor")) return "Write, compile, and run code in our interactive playground.";
    if (path.startsWith("/progress")) return "Analyze your daily practice history and unlock milestone badges.";
    if (path.startsWith("/resume-analyzer")) return "Upload your resume to get instant ATS scoring and feedback.";
    if (path.startsWith("/analytics")) return "Deep dive into your strengths and weaknesses.";
    if (path.startsWith("/voice-interview")) return "Speak your answers to real-world behavioral questions.";
    if (path.startsWith("/ai-review")) return "Paste your solution to get comprehensive quality metrics.";
    return "Prepare smarter with AI.";
  };

  return (
    <header className="w-full flex flex-col md:flex-row md:items-center md:justify-between gap-4 mb-8">
      {/* Title block */}
      <div>
        <h1 className="text-3xl font-extrabold tracking-tight bg-gradient-to-r from-white via-zinc-100 to-zinc-400 bg-clip-text text-transparent">
          {getPageTitle(location.pathname)}
        </h1>
        <p className="text-zinc-400 text-sm mt-1">
          {getPageSub(location.pathname)}
        </p>
      </div>

      {/* Action items */}
      <div className="flex items-center gap-3 self-end md:self-auto">
        {/* Search */}
        <div className="flex items-center bg-zinc-900/50 border border-zinc-800 focus-within:border-violet-500/50 focus-within:ring-2 focus-within:ring-violet-500/10 rounded-xl px-3.5 py-2 transition-all duration-200 w-60">
          <Search size={16} className="text-zinc-400" />
          <input
            type="text"
            placeholder="Search questions, topics..."
            className="bg-transparent outline-none ml-2 text-xs text-zinc-200 placeholder-zinc-500 w-full"
          />
        </div>

        {/* Action button: Notifications */}
        <button className="bg-zinc-900/50 hover:bg-zinc-900 border border-zinc-800 p-2.5 rounded-xl cursor-pointer text-zinc-300 hover:text-white transition duration-200">
          <Bell size={18} />
        </button>

        {/* Action button: Settings */}
        <button className="bg-zinc-900/50 hover:bg-zinc-900 border border-zinc-800 p-2.5 rounded-xl cursor-pointer text-zinc-300 hover:text-white transition duration-200">
          <Settings size={18} />
        </button>

        {/* Vertical divider */}
        <div className="h-6 w-[1px] bg-zinc-800 mx-1" />

        {/* Logout */}
        <button
          onClick={handleLogout}
          className="bg-red-500/10 hover:bg-red-500 text-red-400 hover:text-white border border-red-500/20 hover:border-transparent transition-all duration-200 p-2.5 rounded-xl cursor-pointer"
          title="Sign Out"
        >
          <LogOut size={18} />
        </button>
      </div>
    </header>
  );
};

export default Navbar;